### ISSUE TITLE
Investigate Rendering Performance in Firefox

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#1020]
See main page:

http://www.cirquedusoleil.com/en/welcome.aspx

View it in the inspector:

SWF: [d61b88608d76b835de639687b9390deaa402782f6d211d015b1a330613fab04f](http://swf.codeazur.com.br/#d61b88608d76b835de639687b9390deaa402782f6d211d015b1a330613fab04f) ([Direct Link](http://swf.codeazur.com.br/archive/d6/1b/88/60/d61b88608d76b835de639687b9390deaa402782f6d211d015b1a330613fab04f.swf))

**Comment by tschneidereit** [comment]
Performance seems okay, plus this is not our focus at all, right now.
