### ISSUE TITLE
Only Paint When Necessary 

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#1021]
Enable:

layers.acceleration.draw-fps;true

No repainting should happen here. We're causing lots recompositing for no reason here. I think this is a big source of jank when browsing with the extension enabled.

SWF: [d05ff1cdd0dd52b66ed6b48e7aaa1f74cf5b061d6ff26ae7a2742eaed25a9e33](http://swf.codeazur.com.br/#d05ff1cdd0dd52b66ed6b48e7aaa1f74cf5b061d6ff26ae7a2742eaed25a9e33) ([Direct Link](http://swf.codeazur.com.br/archive/d0/5f/f1/cd/d05ff1cdd0dd52b66ed6b48e7aaa1f74cf5b061d6ff26ae7a2742eaed25a9e33.swf))

**Comment by tschneidereit** [comment]
So stale.
