### ISSUE TITLE
JWPlayer Support

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#1045]
Meta bug to keep track of progress on JWPlayer

This site has a lot of test cases we can use:

http://www.longtailvideo.com/support/jw-player/29237/title-and-dimensions

Just browse through the various examples.

Examples:

http://www.longtailvideo.com/support/jw-player/29239/flash-as-primary/
http://www.thisamericanlife.org/play_full.php?play=111

- [x] Some layout problems in the first example. /cc @claus, @tobeytailor

**Comment by yurydelendik** [comment]
Closed in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1120543
