### ISSUE TITLE
Zombo.com rendering issues and AVM1 TypeError

### ISSUE THREAD

**Issue by cpeterso** [mozilla/shumway#1080]
STR:
1. Load http://www.zombo.com/

RESULT:
The color circles have small black circles on their perimeters that are not present when the website is loaded in Flash. Also, Firefox reports the following JS TypeError in the Web Console:

`"AVM1 error: TypeError: Function.prototype.bind called on incompatible undefined" shumway.js:305`

I am running Shumway 0.7.960.

**Comment by yurydelendik** [comment]
Works for me now.
