### ISSUE TITLE
Stop SWF execution when too many errors are encountered.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#1098]
SWF: [5de16d1f3b9b2a42cd1df9b089bc05c27d9d6d97cc3323c702ff36a17af15182](http://swf.codeazur.com.br/#5de16d1f3b9b2a42cd1df9b089bc05c27d9d6d97cc3323c702ff36a17af15182) ([Direct Link](http://swf.codeazur.com.br/archive/5d/e1/6d/1f/5de16d1f3b9b2a42cd1df9b089bc05c27d9d6d97cc3323c702ff36a17af15182.swf))

**Comment by tschneidereit** [comment]
Ad doesn't work at all, anymore. Including in the Flash Player.
