### ISSUE TITLE
Flash detection not working

### ISSUE THREAD

**Issue by jxp** [mozilla/shumway#113]
I have just tested Shumway on a site and saw no flash content.
This was caused by the site using a Flash detection script that checked 
```
navigator.plugins["Shockwave Flash"].description 
```
to ensure a compatible version of Flash could be found.

I'm not sure what can be done about this as the plugins collection is read-only. The only thing that leaps to mind is having a dummy plug-in that has a name of Shockwave Flash, but that seems messy

**Comment by yurydelendik** [comment]
Closing as duplicate of bug 840439 (will be tracking there)

**Comment by ariscop** [comment]
[bug 867626](https://bugzilla.mozilla.org/show_bug.cgi?id=867626) has been resolved incomplete, should this bug be reopened? having sites refuse to load swf files somewhat limits shumway as a flash alternative
