### ISSUE TITLE
Implement LoadVars class

### ISSUE THREAD

**Issue by saschanaz** [mozilla/shumway#1151]
Apps based on Flash version 6 use LoadVars class to do an HTTP request, but it seems that Shumway does not support LoadVars (as my log says _"AVM1 error: Error: Object "LoadVars" is not found"_)

PS: API document from Adobe http://help.adobe.com/en_US/AS2LCR/Flash_10.0/help.html?content=00001161.html

**Comment by SaschaNaz** [comment]
It seems that we already have `loadVariables` function which is an older alternative of `LoadVars`. Hmm.

**Comment by tschneidereit** [comment]
Correct, this isn't some fundamental issue, it's a case of not-implemented functionality. If you'd be interested in contributing, I'd gladly help you get things set up. Otherwise, we'll get to it in due time.

**Comment by SaschaNaz** [comment]
I think I can try something based on your previous work (#1162). I'll ask some help when I actually start to work. Thanks :) This functionality is required to run DMM's game called Kantai Collection.

**Comment by tschneidereit** [comment]
That would be quite excellent! Either you can ask questions here, or drop by in our IRC channel, #shumway on irc.mozilla.org.
