### ISSUE TITLE
SWF is Super Slow

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#1230]
We need to make sure either we fix the perf here, or give up on these kinds of swifs as they take down the entire browser more or less.

SWF: [76576c069c18a83bc3b873aabf0754dd6ecb56e1cff7bb65d3b2e61d8ee3a588](http://swf.codeazur.com.br/#76576c069c18a83bc3b873aabf0754dd6ecb56e1cff7bb65d3b2e61d8ee3a588) ([Direct Link](http://swf.codeazur.com.br/archive/76/57/6c/06/76576c069c18a83bc3b873aabf0754dd6ecb56e1cff7bb65d3b2e61d8ee3a588.swf))

**Comment by yurydelendik** [comment]
WFM now
