### ISSUE TITLE
color difference 

### ISSUE THREAD

**Issue by nageshkini** [mozilla/shumway#1257]
SWF: [e3326d705135dfec657a2a386d6fdc29d62001cb52569ee9e718ee1c2d966273](http://swf.codeazur.com.br/#e3326d705135dfec657a2a386d6fdc29d62001cb52569ee9e718ee1c2d966273) ([Direct Link](http://swf.codeazur.com.br/archive/e3/32/6d/70/e3326d705135dfec657a2a386d6fdc29d62001cb52569ee9e718ee1c2d966273.swf))

**Comment by tschneidereit** [comment]
This got fixed in the meantime.
