### ISSUE TITLE
stuck at 50%

### ISSUE THREAD

**Issue by nageshkini** [mozilla/shumway#1269]
SWF: [feee05e299fc792973eb8d9097a1f9b63578ba89830695b579e244f6d6559c01](http://swf.codeazur.com.br/#feee05e299fc792973eb8d9097a1f9b63578ba89830695b579e244f6d6559c01) ([Direct Link](http://swf.codeazur.com.br/archive/fe/ee/05/e2/feee05e299fc792973eb8d9097a1f9b63578ba89830695b579e244f6d6559c01.swf))

**Comment by tschneidereit** [comment]
Yeah, this isn't really actionable. The SWF clearly doesn't work outside of its normal embedding, so testing it in the archive isn't useful. Hence, closing this issue.
