### ISSUE TITLE
Selecting an item in shumway doesn't stop the item in shumway as it does on the other player

### ISSUE THREAD

**Issue by nageshkini** [mozilla/shumway#1274]
SWF: [4fa2156cef6e9dd38811a0e8ecdefe2510b3d9193d0c242cba3acef9d772d0bc](http://swf.codeazur.com.br/#4fa2156cef6e9dd38811a0e8ecdefe2510b3d9193d0c242cba3acef9d772d0bc) ([Direct Link](http://swf.codeazur.com.br/archive/4f/a2/15/6c/4fa2156cef6e9dd38811a0e8ecdefe2510b3d9193d0c242cba3acef9d772d0bc.swf))

**Comment by yurydelendik** [comment]
Works for me now. Thank you.
