### ISSUE TITLE
different letters being displayed

### ISSUE THREAD

**Issue by nageshkini** [mozilla/shumway#1290]
SWF: [860eab9472546d8b2b66079b2d926cd9523382bdf03753d6408d61c21515b6f2](http://swf.codeazur.com.br/#860eab9472546d8b2b66079b2d926cd9523382bdf03753d6408d61c21515b6f2) ([Direct Link](http://swf.codeazur.com.br/archive/86/0e/ab/94/860eab9472546d8b2b66079b2d926cd9523382bdf03753d6408d61c21515b6f2.swf))

**Comment by yurydelendik** [comment]
Works for me now. Thank you.
