### ISSUE TITLE
Difference in appearance of Shumway Extension and Flash Player

### ISSUE THREAD

**Issue by CAKCy** [mozilla/shumway#1409]
SWF: [81795335ae386abe7b8f0ee58d3e07d8afb25eb9bdc4ffee5103c0a882484b32](http://swf.codeazur.com.br/#81795335ae386abe7b8f0ee58d3e07d8afb25eb9bdc4ffee5103c0a882484b32) ([Direct Link](http://swf.codeazur.com.br/archive/81/79/53/35/81795335ae386abe7b8f0ee58d3e07d8afb25eb9bdc4ffee5103c0a882484b32.swf))

1. The bars' colors of Shumway are slightly darker than those of the Flash player.
2. Text legend text of the x-axis of the graph is incorrect: It reads "Variable Text" instead of the labels appearing on the Flash Player

**Comment by yurydelendik** [comment]
Looks good now.

![screen shot 2015-06-11 at 10 17 26 am](https://cloud.githubusercontent.com/assets/1523410/8110632/e8bcaaaa-1022-11e5-89df-0eac9d663cf3.png)

Closing as fixed
