### ISSUE TITLE
No movement, no flashing

### ISSUE THREAD

**Issue by jssellers** [mozilla/shumway#1413]
SWF: [eaf77f685ce65287f3b5f8f472c1bbcaa004f1449b9e6ba554bb74377fa04b96](http://swf.codeazur.com.br/#eaf77f685ce65287f3b5f8f472c1bbcaa004f1449b9e6ba554bb74377fa04b96) ([Direct Link](http://swf.codeazur.com.br/archive/ea/f7/7f/68/eaf77f685ce65287f3b5f8f472c1bbcaa004f1449b9e6ba554bb74377fa04b96.swf))

Issue URL-https://github.com/mozilla/shumway/issues/1413

The firefles in the animation didn't fly around or change color like in the other player. they glowed one color and were still. Even the red one.

**Comment by yurydelendik** [comment]
Works for me now. Thank you.
