### ISSUE TITLE
Animation starts correctly but fails to loop back.

### ISSUE THREAD

**Issue by Evpok** [mozilla/shumway#1471]
At least that's what it looks like.

SWF: [dd4369e279f78efb970c33253526995445da581e0042d12ebf875e9da2b8935b](http://swf.codeazur.com.br/#dd4369e279f78efb970c33253526995445da581e0042d12ebf875e9da2b8935b) ([Direct Link](http://swf.codeazur.com.br/archive/dd/43/69/e2/dd4369e279f78efb970c33253526995445da581e0042d12ebf875e9da2b8935b.swf))

First time reporting an issue in Shumway, I hope I did it right.

**Comment by yurydelendik** [comment]
Works for me now. Thanks.
