### ISSUE TITLE
the flashing white beam in "Get your coupon" run only once

### ISSUE THREAD

**Issue by MrX1980** [mozilla/shumway#1494]
SWF: [5f2d5d1a1555790caf0030be048d4ba7949c7866026d6282f8603d37ce1e6270](http://swf.codeazur.com.br/#5f2d5d1a1555790caf0030be048d4ba7949c7866026d6282f8603d37ce1e6270) ([Direct Link](http://swf.codeazur.com.br/archive/5f/2d/5d/1a/5f2d5d1a1555790caf0030be048d4ba7949c7866026d6282f8603d37ce1e6270.swf))

Mozilla/5.0 (Windows NT 6.3; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0
browser.startup.homepage_override.buildID = 20140722030201

![shumway_0003](https://cloud.githubusercontent.com/assets/1387902/3665480/4e06fb0e-11e6-11e4-9e35-9deab06616b0.PNG)

**Comment by tschneidereit** [comment]
Works now. There are some visual issues, but the bug reported here is fixed.

**Comment by mbebenita** [comment]
@tschneidereit should we re-purpose bugs? (Rename them?)

**Comment by tschneidereit** [comment]
In general, yes. In this particular instance, we're tracking the remaining issues in various places already, so I don't see the value in re-purposing this bug and thus adding a way in which we're tracking them. I did just file [bug 1136829](https://bugzilla.mozilla.org/show_bug.cgi?id=1136829) because I realized that we didn't yet properly track that part.

**Comment by mbebenita** [comment]
I also notice that the gradient on the white beam is busted. It's easier to file these kinds of SWF specific issues than creating general issues on bugzilla.

**Comment by tschneidereit** [comment]
Right, I had assumed that that might be a filter thing, but it's probably a gradient issue.

I don't understand what you mean by "It's easier to file these kinds of SWF specific issues than creating general issues on bugzilla". Can't we just file SWF-specific issues on bugzilla? If that's harder, you're not doing it right. ;)
