### ISSUE TITLE
the flashing white beam in "Learn More" run only once

### ISSUE THREAD

**Issue by MrX1980** [mozilla/shumway#1496]
SWF: [4d052a104f072a05a5d4d1cb53a1b79d9eeec2e3b141a595c5a2ea8298d57e8f](http://swf.codeazur.com.br/#4d052a104f072a05a5d4d1cb53a1b79d9eeec2e3b141a595c5a2ea8298d57e8f) ([Direct Link](http://swf.codeazur.com.br/archive/4d/05/2a/10/4d052a104f072a05a5d4d1cb53a1b79d9eeec2e3b141a595c5a2ea8298d57e8f.swf))

see also #1494

**Comment by tschneidereit** [comment]
This works now.

**Comment by mbebenita** [comment]
The glow in the back doesn't show up for me.
