### ISSUE TITLE
clock is not animated

### ISSUE THREAD

**Issue by MrX1980** [mozilla/shumway#1508]
SWF: [57f65466259a9544d7ce4dd94791f2031ad7ef6b224dd21602d9e642ea4db271](http://swf.codeazur.com.br/#57f65466259a9544d7ce4dd94791f2031ad7ef6b224dd21602d9e642ea4db271) ([Direct Link](http://swf.codeazur.com.br/archive/57/f6/54/66/57f65466259a9544d7ce4dd94791f2031ad7ef6b224dd21602d9e642ea4db271.swf))

Mozilla/5.0 (Windows NT 5.1; rv:34.0) Gecko/20100101 Firefox/34.0
browser.startup.homepage_override.buildID = 20140723030202
shumway.disabled = false

**Comment by yurydelendik** [comment]
Fixed by PR 2278 and PR 2261
