### ISSUE TITLE
mouse hover effect missing ("Check wait times" underline)

### ISSUE THREAD

**Issue by MrX1980** [mozilla/shumway#1509]
SWF: [1f7d092cf077052bea41f3dc15154ba9954602064dde1eef00119219fbd33543](http://swf.codeazur.com.br/#1f7d092cf077052bea41f3dc15154ba9954602064dde1eef00119219fbd33543) ([Direct Link](http://swf.codeazur.com.br/archive/1f/7d/09/2c/1f7d092cf077052bea41f3dc15154ba9954602064dde1eef00119219fbd33543.swf))

Mozilla/5.0 (Windows NT 5.1; rv:34.0) Gecko/20100101 Firefox/34.0
browser.startup.homepage_override.buildID = 20140723030202
shumway.disabled = false

![shumway_0011](https://cloud.githubusercontent.com/assets/1387902/3674440/b2bd5fbc-1276-11e4-8341-b11794a9b5cf.PNG)

**Comment by tschneidereit** [comment]
The issues described here seem to all be fixed. There are other small problems with the SWFs, but they're tracked elsewhere.
