### ISSUE TITLE
flash player doesn't work in shumway

### ISSUE THREAD

**Issue by elkos** [mozilla/shumway#1532]
SWF: [6954977d11d59926e549efbcf0b554dca3fd543eb64be0cd15fe2215689f6bf6](http://swf.codeazur.com.br/#6954977d11d59926e549efbcf0b554dca3fd543eb64be0cd15fe2215689f6bf6) ([Direct Link](http://swf.codeazur.com.br/archive/69/54/97/7d/6954977d11d59926e549efbcf0b554dca3fd543eb64be0cd15fe2215689f6bf6.swf))

Shumway Ext. doesn't render this one

**Comment by tschneidereit** [comment]
This now works.
