### ISSUE TITLE
Report Problem button not working

### ISSUE THREAD

**Issue by alexandrevicenzi** [mozilla/shumway#1542]
When I click on Report Problem button nothing happens.

This is the button value: data:application/x-moz-playpreview;,application/x-shockwave-flash#

Not sure if Shumway bug or Nightly bug.

Version: 0.9.2419
SO: Windows 8
Browser: Nightly 34.0a1

**Comment by tschneidereit** [comment]
This should long be fixed. Sorry for not replying sooner.
