### ISSUE TITLE
Not all animation is showed, some lags during initial screen show

### ISSUE THREAD

**Issue by onorua** [mozilla/shumway#1644]
SWF: [d8768a6173481e0958fa6ea994b1db2fb425fcca33d75021742c236b080fa0c6](http://swf.codeazur.com.br/#d8768a6173481e0958fa6ea994b1db2fb425fcca33d75021742c236b080fa0c6) ([Direct Link](http://swf.codeazur.com.br/archive/d8/76/8a/61/d8768a6173481e0958fa6ea994b1db2fb425fcca33d75021742c236b080fa0c6.swf))

**Comment by tschneidereit** [comment]
At least with the extension, this now fully works. It logs a lot of AVM1 exception to the console, but those might well be caused by the content, not by Shumway doing anything wrong.
