### ISSUE TITLE
Ledbury shirt ad's text is sharper, less anti-aliased in Shumway than in Flash

### ISSUE THREAD

**Issue by scordsdu** [mozilla/shumway#1647]
SWF: [3d3046e92adb877e6062d70622444b70532b979271903e804666e1da352ac262](http://swf.codeazur.com.br/#3d3046e92adb877e6062d70622444b70532b979271903e804666e1da352ac262) ([Direct Link](http://swf.codeazur.com.br/archive/3d/30/46/e9/3d3046e92adb877e6062d70622444b70532b979271903e804666e1da352ac262.swf))

Shumway is brighter whereas Flashplayer has a yellowy ting with a gradient that appears to spill slightly into the Shumway Edge respectively

**Comment by tschneidereit** [comment]
This looks completely identical, so I'm going to close this.
