### ISSUE TITLE
Halts midway through

### ISSUE THREAD

**Issue by gaddman** [mozilla/shumway#1670]
SWF: [f20c3ac44195c33b12a95ee946bdf7a77d38fba3d0b5c8fec8b0462c182415bc](http://swf.codeazur.com.br/#f20c3ac44195c33b12a95ee946bdf7a77d38fba3d0b5c8fec8b0462c182415bc) ([Direct Link](http://swf.codeazur.com.br/archive/f2/0c/3a/c4/f20c3ac44195c33b12a95ee946bdf7a77d38fba3d0b5c8fec8b0462c182415bc.swf))

**Comment by tschneidereit** [comment]
That's exactly what we do now, and indeed, the ad now runs through. Some visual differences, but by and large it works.
