### ISSUE TITLE
Lines are displayed immediately, not drawn progressively

### ISSUE THREAD

**Issue by gaddman** [mozilla/shumway#1676]
SWF: [3331f7afe052bfd2a9d70497503657dd390c446af94269c049a6cac03078bee7](http://swf.codeazur.com.br/#3331f7afe052bfd2a9d70497503657dd390c446af94269c049a6cac03078bee7) ([Direct Link](http://swf.codeazur.com.br/archive/33/31/f7/af/3331f7afe052bfd2a9d70497503657dd390c446af94269c049a6cac03078bee7.swf))

Each line that makes up the building graphic appears immediately as a complete line under Shumway, while Adobe draws them progressively, from one end to the other.

**Comment by yurydelendik** [comment]
Bug 1063400 is fixed. The ad looks good for me.
