### ISSUE TITLE
SWF only plays in shumway but not in flash player.

### ISSUE THREAD

**Issue by vijaykm2** [mozilla/shumway#1680]
SWF: [e640e116793644075d660bcab4a40e6b63b1060cc08ad9be3ad933739d2e6562](http://swf.codeazur.com.br/#e640e116793644075d660bcab4a40e6b63b1060cc08ad9be3ad933739d2e6562) ([Direct Link](http://swf.codeazur.com.br/archive/e6/40/e1/16/e640e116793644075d660bcab4a40e6b63b1060cc08ad9be3ad933739d2e6562.swf))

**Comment by yurydelendik** [comment]
Works for me in Shumway and FP.
