### ISSUE TITLE
Extension and Flash versions fail to load

### ISSUE THREAD

**Issue by BrettHansen** [mozilla/shumway#1729]
SWF: [26369cf69ad3b6a93b489f99831164b0de4147a5d52b29630458e03461c534a7](http://swf.codeazur.com.br/#26369cf69ad3b6a93b489f99831164b0de4147a5d52b29630458e03461c534a7) ([Direct Link](http://swf.codeazur.com.br/archive/26/36/9c/f6/26369cf69ad3b6a93b489f99831164b0de4147a5d52b29630458e03461c534a7.swf))

Both the Shumway Extension and Flash Player frames show the text, "Loading Menu..." then very briefly the status of a download, "Loading Menu 58K / 58K" and then both frames show the text, "Load Error".  This occurred each time that I loaded the page and I wasn't able to affect a different outcome.

The only difference between the players is that the Shumway frame would occasionally appear to skip the "Loading Menu 58K / 58K" text, presumably because it downloaded too fast for me to see it.

**Comment by tschneidereit** [comment]
Thanks for the report. Given that there's no difference between Flash and Shumway, we can't really do much here, so I'm going to close the issue.
