### ISSUE TITLE
Nothing happens for both shumway and flash. It is stuck in the Botaniculata screen.

### ISSUE THREAD

**Issue by eniemrahc** [mozilla/shumway#1838]
SWF: [feee05e299fc792973eb8d9097a1f9b63578ba89830695b579e244f6d6559c01](http://swf.codeazur.com.br/#feee05e299fc792973eb8d9097a1f9b63578ba89830695b579e244f6d6559c01) ([Direct Link](http://swf.codeazur.com.br/archive/fe/ee/05/e2/feee05e299fc792973eb8d9097a1f9b63578ba89830695b579e244f6d6559c01.swf))

**Comment by tschneidereit** [comment]
Given that there's no difference between Flash's and Shumway's behavior, there's nothing for us to do here.
