### ISSUE TITLE
When click learn more, both takes 4-5 seconds before it responds and redirect the page.

### ISSUE THREAD

**Issue by eniemrahc** [mozilla/shumway#1839]
SWF: [c530594211ca5060c2684dd405a1c46ddce79f9c7b2107e4517b440b9d11fb7b](http://swf.codeazur.com.br/#c530594211ca5060c2684dd405a1c46ddce79f9c7b2107e4517b440b9d11fb7b) ([Direct Link](http://swf.codeazur.com.br/archive/c5/30/59/42/c530594211ca5060c2684dd405a1c46ddce79f9c7b2107e4517b440b9d11fb7b.swf))

**Comment by tschneidereit** [comment]
This doesn't show anything for me, anymore. But from the description, it sounds like it never did anything different in Shumway from what it did in Flash, so, closing.
