### ISSUE TITLE
No graphics displayed for both shumway and flash. Just plain white background.

### ISSUE THREAD

**Issue by eniemrahc** [mozilla/shumway#1841]
SWF: [5ae8ea4ec2507a6b847967554e45e5064f7458fd89d8305825451b5313010455](http://swf.codeazur.com.br/#5ae8ea4ec2507a6b847967554e45e5064f7458fd89d8305825451b5313010455) ([Direct Link](http://swf.codeazur.com.br/archive/5a/e8/ea/4e/5ae8ea4ec2507a6b847967554e45e5064f7458fd89d8305825451b5313010455.swf))

**Comment by tschneidereit** [comment]
Given that there's no difference between Flash's and Shumway's behavior, there's nothing for us to do here.
