### ISSUE TITLE
Nothing happens when click the play button for both shumway and flash.

### ISSUE THREAD

**Issue by eniemrahc** [mozilla/shumway#1842]
SWF: [b1270a163a9feebac8f6e8b12b63ebbddcefda0850a63bc6ea2029adc1fd30c3](http://swf.codeazur.com.br/#b1270a163a9feebac8f6e8b12b63ebbddcefda0850a63bc6ea2029adc1fd30c3) ([Direct Link](http://swf.codeazur.com.br/archive/b1/27/0a/16/b1270a163a9feebac8f6e8b12b63ebbddcefda0850a63bc6ea2029adc1fd30c3.swf))

**Comment by tschneidereit** [comment]
Given that there's no difference between Flash's and Shumway's behavior, there's nothing for us to do here.
