### ISSUE TITLE
Nothing happens for both shumway and flash.

### ISSUE THREAD

**Issue by eniemrahc** [mozilla/shumway#1844]
SWF: [5fe977368bb5b23ab20454200dec888ae85eb11185c85894838ee8634e58d4ff](http://swf.codeazur.com.br/#5fe977368bb5b23ab20454200dec888ae85eb11185c85894838ee8634e58d4ff) ([Direct Link](http://swf.codeazur.com.br/archive/5f/e9/77/36/5fe977368bb5b23ab20454200dec888ae85eb11185c85894838ee8634e58d4ff.swf))

**Comment by tschneidereit** [comment]
Given that there's no difference between Flash's and Shumway's behavior, there's nothing for us to do here.
