### ISSUE TITLE
Nothing happens, just continuous loading...

### ISSUE THREAD

**Issue by eniemrahc** [mozilla/shumway#1846]
SWF: [04e921b92143d447022c5c55099762951ecca538f48665fbd674c700f757059b](http://swf.codeazur.com.br/#04e921b92143d447022c5c55099762951ecca538f48665fbd674c700f757059b) ([Direct Link](http://swf.codeazur.com.br/archive/04/e9/21/b9/04e921b92143d447022c5c55099762951ecca538f48665fbd674c700f757059b.swf))

**Comment by tschneidereit** [comment]
Given that there's no difference between Flash's and Shumway's behavior, there's nothing for us to do here.
