### ISSUE TITLE
load is not happening

### ISSUE THREAD

**Issue by filjob** [mozilla/shumway#1909]
The bordeaux background is displayed in the Sumway extension. in the middle upper part of the screen a small horizontal status bar can be seen. It shows the load has just started (see screenshot) but it is not progressing at all what ever time you wait.

SWF: [e51f1029f4819ec2944bce05c9540fc690e81ad583233ae33c1c976a5eae133d](http://swf.codeazur.com.br/#e51f1029f4819ec2944bce05c9540fc690e81ad583233ae33c1c976a5eae133d) ([Direct Link](http://swf.codeazur.com.br/archive/e5/1f/10/29/e51f1029f4819ec2944bce05c9540fc690e81ad583233ae33c1c976a5eae133d.swf))
![loadbar](https://cloud.githubusercontent.com/assets/8741848/5237571/c8ded26c-788d-11e4-9650-20242f1840bd.png)

**Comment by yurydelendik** [comment]
Works for me now. Thanks.
