### ISSUE TITLE
Only loads the background color and stops

### ISSUE THREAD

**Issue by reddieman** [mozilla/shumway#1958]
**Visual Result**
Loads progress bar, only loads the background color
**Expected**
Should load into a interactive menu

SWF: [aba4ece6e17c0a694191d7983ab4a0eefa40578d341c5d41fa114aba3deb2c2a](http://swf.codeazur.com.br/#aba4ece6e17c0a694191d7983ab4a0eefa40578d341c5d41fa114aba3deb2c2a) ([Direct Link](http://swf.codeazur.com.br/archive/ab/a4/ec/e6/aba4ece6e17c0a694191d7983ab4a0eefa40578d341c5d41fa114aba3deb2c2a.swf))

**Comment by yurydelendik** [comment]
Works for me now. Thank you for reporting.
