### ISSUE TITLE
text not disappearing

### ISSUE THREAD

**Issue by PalmerAL** [mozilla/shumway#2022]
SWF: [c0da53a5f62b06161fad0f1eed0cd6be8f072346bdcab64e55731390122789d5](http://swf.codeazur.com.br/#c0da53a5f62b06161fad0f1eed0cd6be8f072346bdcab64e55731390122789d5) ([Direct Link](http://swf.codeazur.com.br/archive/c0/da/53/a5/c0da53a5f62b06161fad0f1eed0cd6be8f072346bdcab64e55731390122789d5.swf))
As the ad changes frames, the old text does not disappear - the new text is just layered over the old text.

**Comment by yurydelendik** [comment]
Fixed by #2123
