### ISSUE TITLE
Feature Request: Add Linux to supported platforms

### ISSUE THREAD

**Issue by rilian-la-te** [mozilla/shumway#2069]
Shumway works on it

**Comment by tschneidereit** [comment]
We will do that soon. We're working on getting an absolutely minimal case enabled by default in Nightly wherever we know that it really does work. Our first test case is the video player on Amazon. For Linux, the problem with that is that we cannot rely on having a suitable video decoder, so we're conservative for this first step.

That said, you can still just set `shumway.disabled` to `false` on Linux and it will be enabled everywhere.

**Comment by tschneidereit** [comment]
Closing this as we're tracking things in https://bugzilla.mozilla.org.
