### ISSUE TITLE
Firefox is crashing trying to convert some swf

### ISSUE THREAD

**Issue by neuromancer** [mozilla/shumway#2106]
Firefox crashes trying to convert a swf inside this website:

    http://www.dnatube.com/video/1837/Mythbusters-Mc-Guyver-Special-Sodium--Metal-Explosion

I'm running Firefox 31 with Shumway 0.10.227 (last updated: 03/09/15). My OS is Ubuntu 14.04 (x86_64). Some useful debugging information (collected using -g):

    ...
    [Nuevo Thread 0x7fffb97ff700 (LWP 1308)]
    [Nuevo Thread 0x7fffb8ffe700 (LWP 1309)]
    [Nuevo Thread 0x7fffb84f9700 (LWP 1310)]
    [Nuevo Thread 0x7fffb5eff700 (LWP 1311)]
    [Nuevo Thread 0x7ffeb29ff700 (LWP 1312)]
    ShumwayStreamConverter.js: Timeout during shumway instance initialization
    [Nuevo Thread 0x7ffdae0ff700 (LWP 1313)]
    [Thread 0x7fffcb5fd700 (LWP 1295) terminado]
    [Nuevo Thread 0x7fffcb5fd700 (LWP 1314)]
    [Thread 0x7ffdae0ff700 (LWP 1313) terminado]
    [Nuevo Thread 0x7ffdae0ff700 (LWP 1315)]
    [Nuevo Thread 0x7ffdab5ff700 (LWP 1316)]
    
    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff26da13a in ?? () from /usr/lib/firefox/libxul.so
    (gdb) bt
    #0  0x00007ffff26da13a in ?? () from /usr/lib/firefox/libxul.so
    #1  0x00007ffff26db10c in ?? () from /usr/lib/firefox/libxul.so
    #2  0x00007ffff1d113b8 in NS_InvokeByIndex () from /usr/lib/firefox/libxul.so
    #3  0x00007ffff25ac91b in ?? () from /usr/lib/firefox/libxul.so
    #4  0x00007ffff25b13ff in ?? () from /usr/lib/firefox/libxul.so
    #5  0x00007ffff34414e8 in ?? () from /usr/lib/firefox/libxul.so
    #6  0x00007ffff343a68a in ?? () from /usr/lib/firefox/libxul.so
    #7  0x00007ffff3441143 in ?? () from /usr/lib/firefox/libxul.so
    #8  0x00007ffff344139b in ?? () from /usr/lib/firefox/libxul.so
    #9  0x00007ffff3441994 in ?? () from /usr/lib/firefox/libxul.so
    #10 0x00007ffff3397cf2 in ?? () from /usr/lib/firefox/libxul.so
    #11 0x00007ffff33ee9a1 in js::CrossCompartmentWrapper::call(JSContext*, JS::Handle<JSObject*>, JS::CallArgs const&) () from /usr/lib/firefox/libxul.so
    #12 0x00007ffff339d559 in js::proxy_Call(JSContext*, unsigned int, JS::Value*) () from /usr/lib/firefox/libxul.so
    #13 0x00007ffff3441620 in ?? () from /usr/lib/firefox/libxul.so
    #14 0x00007ffff343a68a in ?? () from /usr/lib/firefox/libxul.so
    #15 0x00007ffff3441143 in ?? () from /usr/lib/firefox/libxul.so
    #16 0x00007ffff344139b in ?? () from /usr/lib/firefox/libxul.so
    #17 0x00007ffff3441994 in ?? () from /usr/lib/firefox/libxul.so
    #18 0x00007ffff3397cf2 in ?? () from /usr/lib/firefox/libxul.so
    #19 0x00007ffff33ee9a1 in js::CrossCompartmentWrapper::call(JSContext*, JS::Handle<JSObject*>, JS::CallArgs const&) () from /usr/lib/firefox/libxul.so
    #20 0x00007ffff339d559 in js::proxy_Call(JSContext*, unsigned int, JS::Value*) () from /usr/lib/firefox/libxul.so
    #21 0x00007ffff3441620 in ?? () from /usr/lib/firefox/libxul.so
    #22 0x00007ffff3441994 in ?? () from /usr/lib/firefox/libxul.so
    #23 0x00007ffff330a53a in ?? () from /usr/lib/firefox/libxul.so
    #24 0x00007ffff2582c12 in ?? () from /usr/lib/firefox/libxul.so
    #25 0x00007ffff34414e8 in ?? () from /usr/lib/firefox/libxul.so
    #26 0x00007ffff343a68a in ?? () from /usr/lib/firefox/libxul.so
    #27 0x00007ffff3441143 in ?? () from /usr/lib/firefox/libxul.so
    #28 0x00007ffff344139b in ?? () from /usr/lib/firefox/libxul.so
    #29 0x00007ffff3338aec in ?? () from /usr/lib/firefox/libxul.so
    #30 0x00007ffff34414e8 in ?? () from /usr/lib/firefox/libxul.so
    #31 0x00007ffff343a68a in ?? () from /usr/lib/firefox/libxul.so
    #32 0x00007ffff3441143 in ?? () from /usr/lib/firefox/libxul.so
    #33 0x00007ffff344139b in ?? () from /usr/lib/firefox/libxul.so
    #34 0x00007ffff3338aec in ?? () from /usr/lib/firefox/libxul.so
    #35 0x00007ffff34414e8 in ?? () from /usr/lib/firefox/libxul.so
    #36 0x00007ffff343a68a in ?? () from /usr/lib/firefox/libxul.so
    #37 0x00007ffff3441143 in ?? () from /usr/lib/firefox/libxul.so
    #38 0x00007ffff344139b in ?? () from /usr/lib/firefox/libxul.so
    #39 0x00007ffff3441994 in ?? () from /usr/lib/firefox/libxul.so
    #40 0x00007ffff35d173a in ?? () from /usr/lib/firefox/libxul.so
    #41 0x00007ffff7e0e2f0 in ?? ()
    #42 0xfffbfffe00000068 in ?? ()
    #43 0x00007fffffff02b8 in ?? ()
    #44 0x00007fffffff0430 in ?? ()
    #45 0xfff9000000000000 in ?? ()
    #46 0x00007ffff54f0c00 in ?? () from /usr/lib/firefox/libxul.so
    #47 0x00007fffdea33d60 in ?? ()
    #48 0x00007fffbb56dd87 in ?? ()
    #49 0x0000000000000402 in ?? ()
    #50 0x00007fffffff03f0 in ?? ()
    #51 0x00007ffdaa653f58 in ?? ()
    #52 0x0000000000000000 in ?? ()
    (gdb) x/i $rip
    => 0x7ffff26da13a:	mov    (%rdi),%rax
    (gdb) info registers 
    rax            0x0	0
    rbx            0x7ffffffe97d8	140737488263128
    rcx            0x7fffe0d09af0	140736965155568
    rdx            0x0	0
    rsi            0x7ffffffe97d8	140737488263128
    rdi            0x0	0
    rbp            0x0	0x0
    rsp            0x7ffffffe9530	0x7ffffffe9530
    r8             0x0	0
    r9             0x7ffffffe9ac8	140737488263880
    r10            0x5	5
    r11            0x4	4
    r12            0x7fffc1780d80	140736439258496
    r13            0x0	0
    r14            0x7ffffffe99f8	140737488263672
    r15            0x1	1
    rip            0x7ffff26da13a	0x7ffff26da13a
    eflags         0x10246	[ PF ZF IF RF ]
    cs             0x33	51
    ss             0x2b	43
    ds             0x0	0
    es             0x0	0
    fs             0x0	0
    gs             0x0	0

**Comment by yurydelendik** [comment]
Do you have a crash with FF36 or FF39?

**Comment by neuromancer** [comment]
Uhm, it was fixed. I'm closing this.
