### ISSUE TITLE
Continual, repeated AVM1 function generation

### ISSUE THREAD

**Issue by nnethercote** [mozilla/shumway#2122]
I found that  [this ad](http://areweflashyet.com/swfs/1e902e33c40af1d1f6296bde21379600b35576a027cc888f78c5afe792db04e68b6e57671704aeee2814ee0e061608d386021a7985fb8e17a041e1658a39e3f7.swf) has terrible performance.

It causes Firefox to use a full CPU all the time. The AVM1 interpreter is continually generating functions. I inserted a `dump(fn)` at the end of ActionsDataCompiler.generate() and found that lots of them are repeated endlessly. Here's one such function:
```
return function avm1gen_f2i0(ectx) {
var position = 0;
var checkTimeAfter = 0;
var constantPool = ectx.constantPool, registers = ectx.registers,
stack = ectx.stack;
while (!ectx.isEndOfActions) {
if (checkTimeAfter <= 0) { checkTimeAfter = 1000; checkTimeout(ectx); }
switch(position) {
 case 0:
  stack.push("",1);
  calls.ActionGetProperty(ectx);
  stack.push("tyakuti");
  calls.ActionGetVariable(ectx);
  calls.ActionGreater(ectx);
  calls.ActionNot(ectx);
  if (!!stack.pop()) { position = 48; checkTimeAfter -= 7; break; }
  calls.ActionGoToLabel(ectx,["tyakuti",true]);
  position = 57;
  checkTimeAfter -= 9;
  break;
 case 48:
  calls.ActionGoToLabel(ectx,["fall",true]);
  position = 57;
  checkTimeAfter -= 1;
  break;
 default: ectx.isEndOfActions = true; break;
}
}
return stack.pop();};//# sourceURL=avm1gen-f2i0
```

**Comment by yurydelendik** [comment]
The AVM1 functions are cached properly now, but that does not help with CPU. Looks like all CPU is spent in the GFX backend. Opening https://bugzilla.mozilla.org/show_bug.cgi?id=1146593
