### ISSUE TITLE
WeakList uses deprecated netscape.security.PrivilegeManager.enablePrivilege

### ISSUE THREAD

**Issue by zackw** [mozilla/shumway#2124]
The implementation of `WeakList` (in `src/base/utilities.ts`) attempts to use `netscape.security.PrivilegeManager` -- this was removed from the platform in Firefox 17: see https://developer.mozilla.org/en-US/Firefox/Releases/17/Site_compatibility#Security As such, all the code dependent on that test was probably dead when it was written.

The fallback (which is what gets used all the time) seems to be a regular old (non-weak) list, so not only is there a bunch of dead code that raises eyebrows when grepping, the class doesn't even fulfill its contract, unless that's what the manual reference counting crud is about.

(Sadly, it does not appear possible to implement `WeakList` on top of Harmony `WeakMap`, because there is no exposed way to iterate over surviving elements.)

**Comment by cpeterso** [comment]
Good catch! I cloned this bug to Bugzilla because we're trying to consolidate our bugs there:

https://bugzilla.mozilla.org/show_bug.cgi?id=1145499

**Comment by zackw** [comment]
I filed the bug here because the code checked into m-c appears to be machine-generated, not the proper source.  Thanks for clarification.

**Comment by yurydelendik** [comment]
See https://github.com/mozilla/shumway/pull/2130
