### ISSUE TITLE
RegExp string matching bugs

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#2149]
Some Tamarin acceptance tests fail on String matching. This is follow up work to the reg exp patch.

**Comment by tobytailor** [comment]
All String matching test fails should be fixed by https://github.com/mozilla/shumway/commit/bcb223f6f0f74432979db96d5f310ec669baa724.

**Comment by tschneidereit** [comment]
> All String matching test fails should be fixed by bcb223f.

Except for the new failures introduced by not supporting the generic versions of the String methods anymore, yes ;) Fixed by follow-up commits.
