### ISSUE TITLE
FF 40 disable Shumway

### ISSUE THREAD

**Issue by toblerone1963** [mozilla/shumway#2342]
Hello, Shumway is [not signed](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct), so FF40 disabled it. Can you change that ?

![screen](https://cloud.githubusercontent.com/assets/5781292/9292841/1c06bf3a-440e-11e5-91be-eb500fe60aba.png)

Thanks, keep up the good work !

**Comment by timvandermeij** [comment]
This is a duplicate of #2329.

**Comment by timvandermeij** [comment]
@yurydelendik This issue can be closed now that Shumway is signed too.

**Comment by yurydelendik** [comment]
Closing as duplicate of #2329.
