### ISSUE TITLE
Is the development frozen?

### ISSUE THREAD

**Issue by SaschaNaz** [mozilla/shumway#2412]
I'm seeing only five commits since October 1. https://github.com/mozilla/shumway/graphs/contributors?from=2015-10-01&to=2016-01-30&type=c

What happened? Is it frozen because Flash is dying too quickly?

**Comment by Sintendo** [comment]
I'd like to know more as well. Even asked about it [on Reddit](https://www.reddit.com/r/firefox/comments/3vbtf9/is_shumway_dead/) a few months ago, hoping for someone to shed light on this matter.

**Comment by evickery** [comment]
No insider knowledge here, but I did see that on bugzilla all shumway bugs were reclassified as "Firefox Graveyard". So looks like Mozilla no longer backing development, maybe up to contributors here to keep it going.

**Comment by cpeterso** [comment]
Mozilla is not actively working on Shumway right now. We have limited resources and other product features are higher priority than Flash compatibility.
