### ISSUE TITLE
Cannot install on Firefox 48/49 because plugin is not signed

### ISSUE THREAD

**Issue by PeopleInside** [mozilla/shumway#2428]
I cannot install on Firefox because plugin is not signed. This is the message Firefox give to me.

**Comment by ghost** [comment]
http://www.ghacks.net/2016/08/14/override-firefox-add-on-signing-requirement/
or use Firefox Aurora (developer preview) / Nightly
or sign addon for yourself.

**Comment by PeopleInside** [comment]
Never trust disable the protection of Firefox. Thank anyway. I have solved issue with flash for now so continue to use flash for now. Thanks... this is just to inform the component plug in not work with standard Firefox.

**Comment by Efreak** [comment]
I signed the addon for myself, and it's fairly simple to do. Just follow the instructions [here](https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Getting_Started_%28jpm%29). IIRC, the key commands are `jpm xpi` and `jpm sign`. Alternatively, you can upload an xpm file [here](https://addons.mozilla.org/en-US/developers/addon/submit/2) (copy the link, because it won't redirect automatically after signin)

**Comment by dzmitry-lahoda** [comment]
Why this addon not signed or not posted here https://addons.mozilla.org/ first of all, at least as alpha?

**Comment by ShapeShifter499** [comment]
I agree with @asd-and-Rizzo it should be on https://addons.mozilla.org somewhere.

**Comment by Efreak** [comment]
Since so many people seem to want it, I've uploaded my signed copy [to a gist](https://gist.github.com/d82c95894d9a5a8b7094d95a76de29da).

**Comment by ShapeShifter499** [comment]
@Efreak is this the absolute latest copy?

**Comment by Efreak** [comment]
I *think* created it *after* the most recent change to this repo, so it should be. The xpi file and the AMO email that it passed automated tests are both dated 8/5/16. However, I can't guarantee it, as I no longer have the VM I used to build it. You may be able to verify it by building the addon yourself, then unzipping and comparing the contents of your and my xpi files.

**Comment by yurydelendik** [comment]
Closing as fixed
