### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by SoniEx2** [mozilla/shumway#2429]

**Comment by lemmabit** [comment]
[I'm afraid not.](https://bugzilla.mozilla.org/show_bug.cgi?id=1243870)

**Comment by lemmabit** [comment]
[More information here.](http://www.ghacks.net/2016/02/23/flash-replacement-shumway-is-as-good-as-dead/)

**Comment by SoniEx2** [comment]
Sad. I wanted to use Shumway as a library to "automagically" port flash to HTML5, whether the user has flash installed or not.

**Comment by yurydelendik** [comment]
Closing as answered
