### ISSUE TITLE
Rename shumway to shamwow

### ISSUE THREAD

**Issue by linuxnoob69** [mozilla/shumway#2433]
![shumway](https://cloud.githubusercontent.com/assets/24971000/21739820/9c8f8478-d45b-11e6-9bde-f98f7c6e7713.png)
Shumway is really hard to remember, so I suggest this project be renamed to shamwow. Instead of picking up disgusting dishwater you've clumsily spilled everywhere, shumway picks up old technology.

> mozilla shamwow or whatever won't install
> shumway
> I'm calling it shamwow from now on

In addition to being easier to remember, both old informercial and Vince Offer fans will find this great project by accident and be approximately 100% more likely to contribute.

So if someone would just `:%s/shumway/shamwow/g` that'd be great. Great work lads, keep it up.

**Comment by yurydelendik** [comment]
> Shumway is really hard to remember,

No STR provided. Closing as incomplete.
