### ISSUE TITLE
Would open sourcing Flash help the project?

### ISSUE THREAD

**Issue by pakastin** [mozilla/shumway#2438]
Hi guys!

Do you think open sourcing Flash would help the project? What would you need from Adobe?

https://github.com/pakastin/open-source-flash

**Comment by yurydelendik** [comment]
> Do you think open sourcing Flash would help the project? What would you need from Adobe?

Probably it will help. My personal opinion that any useful open source project needs proper licensing and accessible and complete source code.

I guess we can close this as answered, since we cannot do anything on this project end.

**Comment by pakastin** [comment]
Ok, thanks!
