### ISSUE TITLE
JW Player Stays empty

### ISSUE THREAD

**Issue by yoshimo** [mozilla/shumway#415]
JW Player, as used for example on this public radio podcast website:
http://www.br-online.de/podcast/video-download/bayerisches-fernsehen/mp3-download-podcast-kino-kino.shtml 

is using JW Player according to the menu of the player.
Source seems to be available at:http://developer.longtailvideo.com/trac/browser
Why the Extension doesn't log "hey this api is missing", is sad, but hopefully you can make use of the .as files on that repository to support the flash version of this player (they offer both flash and html5 lately)

**Comment by evickery** [comment]
Name 	Firefox
Version 	40.0a1
Build ID 	20150510030207
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:40.0) Gecko/20100101 Firefox/40.0
Shumway 0.11.23 

works fine for me

**Comment by yoshimo** [comment]
it was failing several Shumway revisions ago, solved by now
