### ISSUE TITLE
SpongeBob Almost Works

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#460]
http://swf.codeazur.com.br/archive/4f/58/6b/f2/4f586bf25c81de0e8060280558bbdbd060ce2d4986d0883f7d54656a15caa319.swf

- [ ] Game get's stuck when pressing Newbie mode.
- [ ] Need to refresh page several times before Shumway kicks in.
- [ ] Drop shadow looks busted.

![screen shot 2013-08-01 at 4 34 49 pm](https://f.cloud.github.com/assets/311082/898084/cec7a744-fb02-11e2-8f04-f82d2f956f03.png)

Also see:

http://swf.codeazur.com.br/archive/8d/a0/14/39/8da014394307c9bba9b2c90dd900dfe5135bd07e8a02363a871edda455751b65.swf

- [ ] Clicking Play takes you to a strange URL.

**Comment by tschneidereit** [comment]
Doesn't work at all anymore because we lost support for `_focusrect` in AVM1, filed bug about that. The rest isn't entirely critical, so we don't need to track it here.
