### ISSUE TITLE
Blur filters are not applied.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#464]
The text should start out blurred.

http://swf.codeazur.com.br/archive/69/4a/3b/9a/694a3b9a5a64d604ef7431f842ea6fa85ff6b8d5d51eeef0eee71740def4a164.swf

We have a naive implementation of blur filters, we may want to use asm.js for this. Currently, filters don't seem to be hooked up yet.

@tobeytailor started work on this a while back, not sure what the status is.

**Comment by tschneidereit** [comment]
We need to support filters, but we're tracking that elsewhere.
