### ISSUE TITLE
Broken Eye missing MovieClip.swapDepths

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#476]
Can't click on the eyes.

SWF: [34e337fc371cfcf816abcc4245cbc80ff99aaaf894bd61b0e85ebf0d90dd3381](http://swf.codeazur.com.br/#34e337fc371cfcf816abcc4245cbc80ff99aaaf894bd61b0e85ebf0d90dd3381) ([Direct Link](http://swf.codeazur.com.br/archive/34/e3/37/fc/34e337fc371cfcf816abcc4245cbc80ff99aaaf894bd61b0e85ebf0d90dd3381.swf))

**Comment by yurydelendik** [comment]
Works for me now.
