### ISSUE TITLE
Pixel Snapping?

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#488]
SWF: [1a84f8a0773e3b22a543339f6e0667ac5578a76bd2da15342cb109695d06cba7](http://swf.codeazur.com.br/#1a84f8a0773e3b22a543339f6e0667ac5578a76bd2da15342cb109695d06cba7) ([Direct Link](http://swf.codeazur.com.br/archive/1a/84/f8/a0/1a84f8a0773e3b22a543339f6e0667ac5578a76bd2da15342cb109695d06cba7.swf))

Seems to be jerky, even when turning on smoothing.

Here's a non-smoothed version: http://swf.codeazur.com.br/#d7d3d77d1883a3796a30ab81d82c2394a3641cabe58fb44562de7f020d312ce5

**Comment by tschneidereit** [comment]
Very slightly jerkier than in Flash, but really not much.
