### ISSUE TITLE
Detect poor performance and throttle down.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#493]
We should detect when Shumway is too slow and reduce the frame rate to allow for other content on the page to execute. Currently Shumway causes the Flash player to slow down considerably for this SWF: http://swf.codeazur.com.br/#06aca933384da485707eb9adc4e6d8ec6bf9e0b5fa419b923911db5874d158d2

I guess we can time the render loop and if we can't match the frame rate we should skip rendering some frames.

**Comment by tschneidereit** [comment]
We're tracking similar stuff elsewhere now.
