### ISSUE TITLE
Support GetVariable, SetVariable and GotoFrame on object tag

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/shumway#505]
http://arrixlive.wordpress.com/2005/03/25/javascript-in-love-with-flash-control-swf-from-javascript/
http://web.archive.org/web/20060115144620/http://www.macromedia.com/support/flash/publishexport/scriptingwithflash/scriptingwithflash_03.html

**Comment by tschneidereit** [comment]
Not worth tracking here.
