### ISSUE TITLE
Make Zombotron work.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#624]
Can be run with Chrome --disable-web-security.

- [x] DisplayObjectContainer.removeChild called with a child that has no `_parent`.

Ignoring this takes you past the sword animation and almost to the end of the charging sequence.

- [x] MovieClip.destructChildren fails when `nextDisplayList` is undefined.

**Comment by tschneidereit** [comment]
While this contains the best bug ever (I mean "Zombies run away", how could one beat that?), we don't need to track it here, anymore. Plus, the zombies try to eat you now.
