### ISSUE TITLE
Walking the DisplayList is slow / allocation heavy.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#672]
SWF: [8e7d779c3cbf04cecf6c5dd4176671ceb06ed2e2b130e1ce563bd3fcfc34d45c](http://swf.codeazur.com.br/#8e7d779c3cbf04cecf6c5dd4176671ceb06ed2e2b130e1ce563bd3fcfc34d45c) ([Direct Link](http://swf.codeazur.com.br/archive/8e/7d/77/9c/8e7d779c3cbf04cecf6c5dd4176671ceb06ed2e2b130e1ce563bd3fcfc34d45c.swf))

- [x] getBounds should probably be cached somehow.
- [x] Minimize allocations when walking the display list / getting bounds.
- [x] Concatenated transforms should be stored per element, so _applyCurrentTransform doesn't have to recurse
- [x] _applyCurrentTransform should probably accept arrays of points, so we don't have to call it 4 times every time we want to transform a rectangle.

**Comment by tschneidereit** [comment]
Completely changed, and much better nowadays.
