### ISSUE TITLE
Improve performance when a lot of SWFs are on the page.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#682]
Here's a good example.

http://www.wildbunny.co.uk/blog/2011/04/06/physics-engines-for-dummies/

After the initial load time, each SWF (individually) should render pretty quickly. All the other SWFs should be paused.

- [ ] Part of the problem may be that we seem to be running slower in the extension than in the inspector, which is weird since the extension is an optimized build.
- [ ] Make sure only the SWF in view is being played.
- [ ] We should probably stop all the SWFs when the page is scrolling.

**Comment by tschneidereit** [comment]
We're tracking this stuff elsewhere.
