### ISSUE TITLE
Concat Method not Defined

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#725]
SWF: [313a01b8b019e920995ec3614c8d75af2c27445d31676cffcb3ec79bc6f1c7e7](http://swf.codeazur.com.br/#313a01b8b019e920995ec3614c8d75af2c27445d31676cffcb3ec79bc6f1c7e7) ([Direct Link](http://swf.codeazur.com.br/archive/31/3a/01/b8/313a01b8b019e920995ec3614c8d75af2c27445d31676cffcb3ec79bc6f1c7e7.swf))

**Comment by yurydelendik** [comment]
Works for me now.
