### ISSUE TITLE
Improve PRE Performance

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#893]
SWF: [5064af65cf6983e1119a60c37dc71d2650d07dcbf4ebcd4f72a7ea7ed6770a01](http://swf.codeazur.com.br/#5064af65cf6983e1119a60c37dc71d2650d07dcbf4ebcd4f72a7ea7ed6770a01) ([Direct Link](http://swf.codeazur.com.br/archive/50/64/af/65/5064af65cf6983e1119a60c37dc71d2650d07dcbf4ebcd4f72a7ea7ed6770a01.swf))

- [ ] Also, Wireframe mode looks like it is not drawn correctly, (scaling, and it is a bit clipped). /cc @claus

**Comment by tschneidereit** [comment]
Still a bit slower than in Flash, but not dramatically so. And looks correct.
