### ISSUE TITLE
Text next to clock looks off.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#913]
SWF: [f00ee17f99ca968c854d6c1e585a9e791b49d198e523a1d0dbb563e0cf5a31db](http://swf.codeazur.com.br/#f00ee17f99ca968c854d6c1e585a9e791b49d198e523a1d0dbb563e0cf5a31db) ([Direct Link](http://swf.codeazur.com.br/archive/f0/0e/e1/7f/f00ee17f99ca968c854d6c1e585a9e791b49d198e523a1d0dbb563e0cf5a31db.swf))

**Comment by tschneidereit** [comment]
Works quite well now
