### ISSUE TITLE
Make Mining Truck 2 Work.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#955]
Good news is, game almost works, with a few issues though:

- [ ] Text issues.
- [ ] Space bar doesn't work to drop the load on the truck.
- [ ] Precision errors, for vertical tiles.

![screen shot 2013-11-13 at 11 22 13 am](https://f.cloud.github.com/assets/311082/1534684/f5c01dd0-4c98-11e3-97e2-3abfede7b287.png)

**Comment by tschneidereit** [comment]
Stale
