### ISSUE TITLE
Cache Shape Objects

### ISSUE THREAD

**Issue by mbebenita** [mozilla/shumway#964]
SWF: [3be26310ab36d80ad11b3f1af656e69be21771ecb078dae5c808682844cfe050](http://swf.codeazur.com.br/#3be26310ab36d80ad11b3f1af656e69be21771ecb078dae5c808682844cfe050) ([Direct Link](http://swf.codeazur.com.br/archive/3b/e2/63/10/3be26310ab36d80ad11b3f1af656e69be21771ecb078dae5c808682844cfe050.swf))

We should probably cache display objects that are added and removed by the timeline. Additionally, we can probably cache things like movie clip bounds per frame as well as other information that doesn't change per frame. 

If a display object leaks into AS3, we can clone it.

**Comment by tschneidereit** [comment]
All of this works completely differently now.
